#ifndef ALLCOMMANDS_H
#define ALLCOMMANDS_H
#include "command.h"
#include "commands/add.h"
#include "commands/and.h"
#include "commands/beq.h"
#include "commands/bge.h"
#include "commands/blt.h"
#include "commands/bne.h"
#include "commands/cal.h"
#include "commands/div.h"
#include "commands/draw.h"
#include "commands/end.h"
#include "commands/jal.h"
#include "commands/load.h"
#include "commands/mov.h"
#include "commands/mul.h"
#include "commands/or.h"
#include "commands/pop.h"
#include "commands/push.h"
#include "commands/rem.h"
#include "commands/ret.h"
#include "commands/store.h"
#include "commands/sub.h"
#include "lineid.h"

#endif // !ALLCOMMANDS_H
